export const CREATE_FILTER = 'CREATE_FILTER';
export const CREATE_PRICE_FILTER = 'CREATE_PRICE_FILTER';
export const CREATE_NAME_PATTERN = 'CREATE_NAME_PATTERN';
export const ADD_TO_BASKET='ADD_TO_BASKET';
export const DELETE_FROM_BASKET ='DELETE_FROM_BASKET';
export const CHANGE_CARD_COUNT = 'CHANGE_CARD_COUNT';